profile: Increase program memory segment usage analysis
OpenXiangShan/NEMU pull request #261
Opened 2024-01-29 07:27 UTC by xiaokamikami

When PROGRAM_ANALYSIS is configured, the program's memory segment usage analysis is started and printed or exported to a file. The path is set using --analysis-mem-path, and the analysis is performed in 32MB block units by default

2024-01-29 09:01 UTC, shinezyy requested changes

2024-01-29 09:01 UTC, shinezyy commented on src/monitor/monitor.c
> +          any_mem_file = optarg;
any_mem_file 这个名字太奇怪了，建议改为 memory_region_record_file

2024-01-29 09:01 UTC, shinezyy commented on src/monitor/monitor.c
> +        printf("\t--analysis-mem-path     result output file for analyzing the memory use segment\n");
--analysis-mem-path 建议改为  memory_region_record_file 类似的词汇

2024-01-29 10:27 UTC, xiaokamikami commented
修改好了

2024-01-30 02:06 UTC, shinezyy approved these changes
Ok

2024-01-30 02:06 UTC, merged