support using zstd decompress checkpoint
OpenXiangShan/NEMU pull request #266
Opened 2024-02-19 10:28 UTC by xyyy1420

2024-02-20 06:33 UTC, poemonsense commented on Makefile
> +CFLAGS += -lzstd
Only include the header when CONFIG_MEM_COMPRESS is enabled?

2024-02-20 08:42 UTC, poemonsense commented on Makefile
> +
Unused empty line

2024-02-20 11:22 UTC, poemonsense reviewed
LGTM. Let zyy have a look

2024-02-22 02:31 UTC, shinezyy requested changes

2024-02-22 02:31 UTC, shinezyy commented on src/monitor/image_loader.c
> +    for (uint32_t x = 0; x < output.pos; x++) {
Can we use uint64_t here? U64 might be faster

2024-02-26 09:10 UTC, shinezyy approved these changes

2024-02-26 09:11 UTC, merged